CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`categoryId` int,
	`uuid` varchar(64) NOT NULL,
	`zettelkasten_id` varchar(50),
	`title` varchar(255) NOT NULL,
	`description` text,
	`status` enum('active','completed','archived','on-hold') DEFAULT 'active',
	`startDate` timestamp,
	`endDate` timestamp,
	`tags` text,
	`linkedEntries` text,
	`favorite` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`),
	CONSTRAINT `projects_uuid_unique` UNIQUE(`uuid`),
	CONSTRAINT `projects_zettelkasten_id_unique` UNIQUE(`zettelkasten_id`)
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`categoryId` int,
	`projectId` int,
	`uuid` varchar(64) NOT NULL,
	`zettelkasten_id` varchar(50),
	`title` varchar(255) NOT NULL,
	`description` text,
	`status` enum('todo','in-progress','completed','blocked') DEFAULT 'todo',
	`priority` enum('low','medium','high','urgent') DEFAULT 'medium',
	`dueDate` timestamp,
	`completedDate` timestamp,
	`tags` text,
	`linkedEntries` text,
	`linkedProjectId` int,
	`favorite` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tasks_id` PRIMARY KEY(`id`),
	CONSTRAINT `tasks_uuid_unique` UNIQUE(`uuid`),
	CONSTRAINT `tasks_zettelkasten_id_unique` UNIQUE(`zettelkasten_id`)
);
