export type JohnnyDecimalCategorySeed = {
  areaNumber: number;
  areaName: string;
  areaDescription: string;
  categoryNumber: string;
  categoryName: string;
  categoryDescription: string;
};

export const johnnyDecimalSeeds: JohnnyDecimalCategorySeed[] = [
  {
    areaNumber: 0,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "00.00",
    categoryName: "System Documentation",
    categoryDescription: "Master-key materials, version history, style guides, and governing conventions for the PKM system.",
  },
  {
    areaNumber: 1,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "01.01",
    categoryName: "Master Topic Index",
    categoryDescription: "Alphabetical indexes organized by topic for fast retrieval.",
  },
  {
    areaNumber: 1,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "01.02",
    categoryName: "Master Person Index",
    categoryDescription: "Alphabetical indexes organized by person.",
  },
  {
    areaNumber: 1,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "01.03",
    categoryName: "Master Source Index",
    categoryDescription: "Alphabetical indexes organized by source text or work.",
  },
  {
    areaNumber: 1,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "01.04",
    categoryName: "Chronological Note Index",
    categoryDescription: "Date-ordered finding aid for previously created notes.",
  },
  {
    areaNumber: 2,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "02.01",
    categoryName: "Books to Read",
    categoryDescription: "Priority reading queue for books.",
  },
  {
    areaNumber: 2,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "02.02",
    categoryName: "Articles to Read",
    categoryDescription: "Reading queue for essays, articles, and shorter texts.",
  },
  {
    areaNumber: 2,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "02.03",
    categoryName: "Research Questions",
    categoryDescription: "Open questions and investigation prompts to pursue later.",
  },
  {
    areaNumber: 2,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "02.04",
    categoryName: "Completed Reading Log",
    categoryDescription: "Log of finished books, articles, and completed research intake.",
  },
  {
    areaNumber: 3,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "03.01",
    categoryName: "Note-Taking Methods",
    categoryDescription: "Methods, patterns, and operating rules for taking notes.",
  },
  {
    areaNumber: 3,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "03.02",
    categoryName: "Research Techniques",
    categoryDescription: "Research process guidance, search strategies, and collection techniques.",
  },
  {
    areaNumber: 3,
    areaName: "SYSTEM & META",
    areaDescription: "The infrastructure, indexes, conventions, and queues that keep the knowledge system legible.",
    categoryNumber: "03.03",
    categoryName: "Digital Tools & Workflows",
    categoryDescription: "Tooling notes, digital workflows, and system-operations practices.",
  },
  {
    areaNumber: 10,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "10.01",
    categoryName: "General Vocabulary Lists (A–M)",
    categoryDescription: "General-purpose vocabulary entries for the A–M range.",
  },
  {
    areaNumber: 10,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "10.02",
    categoryName: "General Vocabulary Lists (N–Z)",
    categoryDescription: "General-purpose vocabulary entries for the N–Z range.",
  },
  {
    areaNumber: 10,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "10.03",
    categoryName: "Rare & Archaic Words",
    categoryDescription: "Rare, archaic, or otherwise uncommon vocabulary.",
  },
  {
    areaNumber: 11,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "11.01",
    categoryName: "Word Origins & Histories",
    categoryDescription: "Etymological notes focused on word origins and historical development.",
  },
  {
    areaNumber: 11,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "11.02",
    categoryName: "Root Words & Morphology",
    categoryDescription: "Morphological notes, root systems, and structural language study.",
  },
  {
    areaNumber: 11,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "11.03",
    categoryName: "Language Family Connections",
    categoryDescription: "Cross-language family relationships and etymological links.",
  },
  {
    areaNumber: 12,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "12.01",
    categoryName: "Usage Notes & Distinctions",
    categoryDescription: "Usage notes, distinctions, and applied language guidance.",
  },
  {
    areaNumber: 12,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "12.02",
    categoryName: "Idiomatic Expressions",
    categoryDescription: "Idioms, set phrases, and expression-oriented language notes.",
  },
  {
    areaNumber: 12,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "12.03",
    categoryName: "Rhetorical Devices & Figures of Speech",
    categoryDescription: "Figures of speech, rhetorical techniques, and stylistic devices.",
  },
  {
    areaNumber: 13,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "13.01",
    categoryName: "Academic & Scholarly Terms",
    categoryDescription: "Academic or scholarly terminology and conceptual vocabulary.",
  },
  {
    areaNumber: 13,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "13.02",
    categoryName: "Domain-Specific Vocabularies",
    categoryDescription: "Terminology tied to specific domains, crafts, or disciplines.",
  },
  {
    areaNumber: 13,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "13.03",
    categoryName: "Jargon & Professional Language",
    categoryDescription: "Professional jargon and specialist language in use.",
  },
  {
    areaNumber: 14,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "14.01",
    categoryName: "Latin Terms & Phrases",
    categoryDescription: "Latin words, phrases, and classical references.",
  },
  {
    areaNumber: 14,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "14.02",
    categoryName: "French Terms & Phrases",
    categoryDescription: "French vocabulary, terms, and idiomatic expressions.",
  },
  {
    areaNumber: 14,
    areaName: "LANGUAGE & VOCABULARY",
    areaDescription: "Systematic study of words, usage, etymology, and linguistic patterns.",
    categoryNumber: "14.03",
    categoryName: "Other Languages",
    categoryDescription: "Vocabulary and phrase notes from languages outside the primary focus sets.",
  },
  {
    areaNumber: 20,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "20.01",
    categoryName: "Ancient Philosophy",
    categoryDescription: "Reading notes from ancient philosophy sources.",
  },
  {
    areaNumber: 20,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "20.02",
    categoryName: "Modern Philosophy",
    categoryDescription: "Reading notes from modern philosophy sources.",
  },
  {
    areaNumber: 20,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "20.03",
    categoryName: "Contemporary Philosophy",
    categoryDescription: "Reading notes from contemporary philosophy sources.",
  },
  {
    areaNumber: 21,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "21.01",
    categoryName: "Ancient History",
    categoryDescription: "Reading notes from ancient history materials.",
  },
  {
    areaNumber: 21,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "21.02",
    categoryName: "Medieval & Early Modern History",
    categoryDescription: "Reading notes from medieval and early modern history materials.",
  },
  {
    areaNumber: 21,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "21.03",
    categoryName: "Modern History",
    categoryDescription: "Reading notes from modern history materials, especially 1800 to present.",
  },
  {
    areaNumber: 22,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "22.01",
    categoryName: "Natural Sciences",
    categoryDescription: "Reading notes from natural science sources.",
  },
  {
    areaNumber: 22,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "22.02",
    categoryName: "Social Sciences",
    categoryDescription: "Reading notes from social science sources.",
  },
  {
    areaNumber: 22,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "22.03",
    categoryName: "Mathematics & Logic",
    categoryDescription: "Reading notes from mathematics and logic sources.",
  },
  {
    areaNumber: 23,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "23.01",
    categoryName: "Fiction & Poetry Notes",
    categoryDescription: "Reading notes from fiction, poetry, and related literary works.",
  },
  {
    areaNumber: 23,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "23.02",
    categoryName: "Literary Criticism & Theory",
    categoryDescription: "Reading notes focused on criticism, theory, and interpretation.",
  },
  {
    areaNumber: 23,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "23.03",
    categoryName: "Writing Craft & Technique",
    categoryDescription: "Notes on writing craft, technique, and literary composition.",
  },
  {
    areaNumber: 24,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "24.01",
    categoryName: "Individual Biographies",
    categoryDescription: "Reading notes from biographies of individual figures.",
  },
  {
    areaNumber: 24,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "24.02",
    categoryName: "Collective Biography",
    categoryDescription: "Reading notes on groups, movements, and collective life stories.",
  },
  {
    areaNumber: 24,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "24.03",
    categoryName: "Autobiography & Memoir",
    categoryDescription: "Reading notes from memoirs and autobiographical works.",
  },
  {
    areaNumber: 25,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "25.01",
    categoryName: "Cognitive Psychology",
    categoryDescription: "Reading notes on cognition, mind, and mental processes.",
  },
  {
    areaNumber: 25,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "25.02",
    categoryName: "Social Psychology",
    categoryDescription: "Reading notes on social behavior, influence, and group dynamics.",
  },
  {
    areaNumber: 25,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "25.03",
    categoryName: "Developmental Psychology",
    categoryDescription: "Reading notes on developmental stages and human growth.",
  },
  {
    areaNumber: 26,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "26.01",
    categoryName: "Political Theory",
    categoryDescription: "Reading notes on political philosophy and theory.",
  },
  {
    areaNumber: 26,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "26.02",
    categoryName: "Current Affairs",
    categoryDescription: "Reading notes on current events, public discourse, and social developments.",
  },
  {
    areaNumber: 26,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "26.03",
    categoryName: "Social Movements & Change",
    categoryDescription: "Reading notes on activism, reform, and historical change movements.",
  },
  {
    areaNumber: 27,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "27.01",
    categoryName: "Visual Arts",
    categoryDescription: "Reading notes on visual art and criticism.",
  },
  {
    areaNumber: 27,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "27.02",
    categoryName: "Music & Sound",
    categoryDescription: "Reading notes on music, sound, and auditory aesthetics.",
  },
  {
    areaNumber: 27,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "27.03",
    categoryName: "Aesthetic Theory",
    categoryDescription: "Reading notes on aesthetics, taste, and artistic theory.",
  },
  {
    areaNumber: 28,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "28.01",
    categoryName: "Religious Texts & Theology",
    categoryDescription: "Reading notes on sacred texts, theology, and doctrine.",
  },
  {
    areaNumber: 28,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "28.02",
    categoryName: "Comparative Religion",
    categoryDescription: "Reading notes that compare traditions, beliefs, and practices.",
  },
  {
    areaNumber: 28,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "28.03",
    categoryName: "Spiritual Practice & Mysticism",
    categoryDescription: "Reading notes on contemplative practice, mysticism, and lived spirituality.",
  },
  {
    areaNumber: 29,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "29.01",
    categoryName: "Popular Nonfiction",
    categoryDescription: "Reading notes from popular nonfiction works.",
  },
  {
    areaNumber: 29,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "29.02",
    categoryName: "Articles & Essays",
    categoryDescription: "Reading notes from articles, essays, and shorter nonfiction.",
  },
  {
    areaNumber: 29,
    areaName: "LITERATURE & READING NOTES",
    areaDescription: "Reading notes across philosophy, history, science, literature, politics, religion, and adjacent disciplines.",
    categoryNumber: "29.03",
    categoryName: "Uncategorized Reading Notes",
    categoryDescription: "Reading notes awaiting more precise categorization.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.01",
    categoryName: "Creativity & Art Quotations",
    categoryDescription: "Quotations organized around creativity, making, and art.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.02",
    categoryName: "Knowledge & Learning Quotations",
    categoryDescription: "Quotations organized around knowledge, study, and learning.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.03",
    categoryName: "Truth & Wisdom Quotations",
    categoryDescription: "Quotations organized around truth, judgment, and wisdom.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.04",
    categoryName: "Human Nature Quotations",
    categoryDescription: "Quotations organized around selfhood, motive, and human behavior.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.05",
    categoryName: "Time & Mortality Quotations",
    categoryDescription: "Quotations organized around time, loss, death, and finitude.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.06",
    categoryName: "Love & Relationship Quotations",
    categoryDescription: "Quotations organized around love, attachment, and relationship.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.07",
    categoryName: "Power & Politics Quotations",
    categoryDescription: "Quotations organized around power, politics, and public life.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.08",
    categoryName: "Nature & Environment Quotations",
    categoryDescription: "Quotations organized around nature, place, and environment.",
  },
  {
    areaNumber: 30,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "30.09",
    categoryName: "Miscellaneous Quotations",
    categoryDescription: "General quotation storage when no tighter thematic fit is available yet.",
  },
  {
    areaNumber: 31,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "31.00",
    categoryName: "Quotations by Author (A–F)",
    categoryDescription: "Author-organized quotations for the A–F range.",
  },
  {
    areaNumber: 32,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "32.00",
    categoryName: "Quotations by Author (G–L)",
    categoryDescription: "Author-organized quotations for the G–L range.",
  },
  {
    areaNumber: 33,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "33.00",
    categoryName: "Quotations by Author (M–R)",
    categoryDescription: "Author-organized quotations for the M–R range.",
  },
  {
    areaNumber: 34,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "34.00",
    categoryName: "Quotations by Author (S–Z)",
    categoryDescription: "Author-organized quotations for the S–Z range.",
  },
  {
    areaNumber: 35,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "35.01",
    categoryName: "Poetry Excerpts by Poet",
    categoryDescription: "Poetry excerpts grouped by poet.",
  },
  {
    areaNumber: 35,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "35.02",
    categoryName: "Poetry Excerpts by Theme",
    categoryDescription: "Poetry excerpts grouped by theme or conceptual thread.",
  },
  {
    areaNumber: 36,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "36.01",
    categoryName: "Notable Exchanges",
    categoryDescription: "Dialogues and conversational exchanges worth preserving.",
  },
  {
    areaNumber: 36,
    areaName: "QUOTATIONS & EXCERPTS",
    areaDescription: "Collected quotations, excerpts, poetic fragments, and dialogue organized for retrieval and reuse.",
    categoryNumber: "36.02",
    categoryName: "Interview Excerpts",
    categoryDescription: "Interview passages and conversational excerpts from source material.",
  },
  {
    areaNumber: 40,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "40.01",
    categoryName: "Active Research Projects",
    categoryDescription: "Ongoing research projects and topic-specific investigations.",
  },
  {
    areaNumber: 40,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "40.02",
    categoryName: "Research Project Slot 2",
    categoryDescription: "Reserved active project lane from the master key for additional research work.",
  },
  {
    areaNumber: 40,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "40.03",
    categoryName: "Research Project Slot 3",
    categoryDescription: "Reserved active project lane from the master key for additional research work.",
  },
  {
    areaNumber: 41,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "41.01",
    categoryName: "Observations & Insights",
    categoryDescription: "Research fragments consisting of observations, partial insights, and early captures.",
  },
  {
    areaNumber: 41,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "41.02",
    categoryName: "Questions Worth Exploring",
    categoryDescription: "Open research questions and prompts for follow-up inquiry.",
  },
  {
    areaNumber: 41,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "41.03",
    categoryName: "Hypotheses & Conjectures",
    categoryDescription: "Tentative models, conjectures, and testable hypotheses.",
  },
  {
    areaNumber: 42,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "42.01",
    categoryName: "Literature Reviews by Topic",
    categoryDescription: "Topic-based literature review notes.",
  },
  {
    areaNumber: 42,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "42.02",
    categoryName: "Methodological Reviews",
    categoryDescription: "Reviews of methods, methodologies, and evaluative comparisons.",
  },
  {
    areaNumber: 43,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "43.01",
    categoryName: "Statistics & Facts",
    categoryDescription: "Collected factual evidence, statistics, and supporting data points.",
  },
  {
    areaNumber: 43,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "43.02",
    categoryName: "Case Studies",
    categoryDescription: "Case-study materials and supporting examples.",
  },
  {
    areaNumber: 43,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "43.03",
    categoryName: "Empirical Observations",
    categoryDescription: "Observed evidence and empirically grounded notes.",
  },
  {
    areaNumber: 44,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "44.01",
    categoryName: "Analytical Frameworks",
    categoryDescription: "Framework notes, models, and analytical structures.",
  },
  {
    areaNumber: 44,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "44.02",
    categoryName: "Critical Responses",
    categoryDescription: "Critical response notes, objections, and argumentative counterpoints.",
  },
  {
    areaNumber: 44,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "44.03",
    categoryName: "Synthesis Notes",
    categoryDescription: "Integrative analysis that combines multiple notes or lines of thought.",
  },
  {
    areaNumber: 45,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "45.01",
    categoryName: "Essay Drafts",
    categoryDescription: "Draft essays and extended prose in progress.",
  },
  {
    areaNumber: 45,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "45.02",
    categoryName: "Outlines & Structures",
    categoryDescription: "Outlines, structural maps, and composition scaffolds.",
  },
  {
    areaNumber: 45,
    areaName: "RESEARCH & ORIGINAL THINKING",
    areaDescription: "Original research work, project development, analytical thinking, and writing process materials.",
    categoryNumber: "45.03",
    categoryName: "Writing Notes & Revisions",
    categoryDescription: "Revision notes, writing process reflections, and support materials.",
  },
  {
    areaNumber: 50,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "50.01",
    categoryName: "Epistemological Concepts",
    categoryDescription: "Concept notes about knowledge, belief, evidence, and justification.",
  },
  {
    areaNumber: 50,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "50.02",
    categoryName: "Ontological Concepts",
    categoryDescription: "Concept notes about being, existence, categories, and reality.",
  },
  {
    areaNumber: 50,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "50.03",
    categoryName: "Logical & Mathematical Concepts",
    categoryDescription: "Concept notes in logic, structure, and mathematical thought.",
  },
  {
    areaNumber: 51,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "51.01",
    categoryName: "Cognitive Concepts",
    categoryDescription: "Concept notes related to cognition, reasoning, and perception.",
  },
  {
    areaNumber: 51,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "51.02",
    categoryName: "Emotional & Affective Concepts",
    categoryDescription: "Concept notes related to feeling, mood, and affective life.",
  },
  {
    areaNumber: 51,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "51.03",
    categoryName: "Behavioral Concepts",
    categoryDescription: "Concept notes related to conduct, action, and behavioral patterns.",
  },
  {
    areaNumber: 52,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "52.01",
    categoryName: "Power & Authority",
    categoryDescription: "Concept notes on governance, hierarchy, power, and authority.",
  },
  {
    areaNumber: 52,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "52.02",
    categoryName: "Community & Belonging",
    categoryDescription: "Concept notes on social bonds, belonging, and group life.",
  },
  {
    areaNumber: 52,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "52.03",
    categoryName: "Identity & Self",
    categoryDescription: "Concept notes about selfhood, identity, and personhood.",
  },
  {
    areaNumber: 53,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "53.01",
    categoryName: "Beauty & Sublimity",
    categoryDescription: "Concept notes about beauty, taste, and sublimity.",
  },
  {
    areaNumber: 53,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "53.02",
    categoryName: "Form & Structure",
    categoryDescription: "Concept notes about form, structure, and arrangement.",
  },
  {
    areaNumber: 53,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "53.03",
    categoryName: "Expression & Meaning",
    categoryDescription: "Concept notes about expression, signification, and meaning-making.",
  },
  {
    areaNumber: 54,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "54.01",
    categoryName: "Virtue & Character",
    categoryDescription: "Concept notes on virtue, ethics, and character formation.",
  },
  {
    areaNumber: 54,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "54.02",
    categoryName: "Justice & Fairness",
    categoryDescription: "Concept notes on justice, fairness, and social evaluation.",
  },
  {
    areaNumber: 54,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "54.03",
    categoryName: "Rights & Obligations",
    categoryDescription: "Concept notes on duties, rights, claims, and obligations.",
  },
  {
    areaNumber: 55,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "55.01",
    categoryName: "Natural Science Concepts",
    categoryDescription: "Concept notes rooted in the natural sciences.",
  },
  {
    areaNumber: 55,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "55.02",
    categoryName: "Formal Science Concepts",
    categoryDescription: "Concept notes rooted in logic, mathematics, and other formal sciences.",
  },
  {
    areaNumber: 55,
    areaName: "CONCEPTS & THEORIES",
    areaDescription: "Core concepts, theories, and idea notes organized in a Zettelkasten-style conceptual layer.",
    categoryNumber: "55.03",
    categoryName: "Applied Science Concepts",
    categoryDescription: "Concept notes connected to applied scientific fields and practical sciences.",
  },
  {
    areaNumber: 60,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "60.01",
    categoryName: "Critical Thinking Methods",
    categoryDescription: "Methods for evaluation, reasoning, and analysis.",
  },
  {
    areaNumber: 60,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "60.02",
    categoryName: "Creative Thinking Techniques",
    categoryDescription: "Methods for generative, associative, and creative ideation.",
  },
  {
    areaNumber: 60,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "60.03",
    categoryName: "Problem-Solving Approaches",
    categoryDescription: "Practical approaches to diagnosis, solution-finding, and iterative improvement.",
  },
  {
    areaNumber: 61,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "61.01",
    categoryName: "Qualitative Methods",
    categoryDescription: "Qualitative research methods and interpretive approaches.",
  },
  {
    areaNumber: 61,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "61.02",
    categoryName: "Quantitative Methods",
    categoryDescription: "Quantitative methods, metrics, and measurement approaches.",
  },
  {
    areaNumber: 61,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "61.03",
    categoryName: "Mixed Methods",
    categoryDescription: "Methodological notes that combine qualitative and quantitative approaches.",
  },
  {
    areaNumber: 62,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "62.01",
    categoryName: "Writing Processes",
    categoryDescription: "Processes, routines, and workflows for writing.",
  },
  {
    areaNumber: 62,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "62.02",
    categoryName: "Rhetorical Strategies",
    categoryDescription: "Persuasive, explanatory, and rhetorical communication strategies.",
  },
  {
    areaNumber: 62,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "62.03",
    categoryName: "Communication Principles",
    categoryDescription: "General communication principles and message-design practices.",
  },
  {
    areaNumber: 63,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "63.01",
    categoryName: "Memory Techniques",
    categoryDescription: "Memory systems, recall methods, and retention techniques.",
  },
  {
    areaNumber: 63,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "63.02",
    categoryName: "Note-Taking Systems",
    categoryDescription: "Systems for capturing, structuring, and reviewing notes.",
  },
  {
    areaNumber: 63,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "63.03",
    categoryName: "Reading Strategies",
    categoryDescription: "Approaches to deep reading, skimming, synthesis, and review.",
  },
  {
    areaNumber: 64,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "64.01",
    categoryName: "Artistic Methods",
    categoryDescription: "Creative and artistic working methods.",
  },
  {
    areaNumber: 64,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "64.02",
    categoryName: "Design Thinking",
    categoryDescription: "Design-thinking practices for iteration and problem framing.",
  },
  {
    areaNumber: 64,
    areaName: "METHODS & PRACTICES",
    areaDescription: "Procedural, practical, and methodological knowledge for thinking, research, writing, and creation.",
    categoryNumber: "64.03",
    categoryName: "Innovation Techniques",
    categoryDescription: "Methods for invention, experimentation, and innovation.",
  },
  {
    areaNumber: 70,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "70.00",
    categoryName: "Philosophers",
    categoryDescription: "Person notes for philosophers and philosophical traditions.",
  },
  {
    areaNumber: 71,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "71.00",
    categoryName: "Writers & Poets",
    categoryDescription: "Person notes for writers, poets, and literary figures.",
  },
  {
    areaNumber: 72,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "72.00",
    categoryName: "Scientists",
    categoryDescription: "Person notes for scientists and researchers.",
  },
  {
    areaNumber: 73,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "73.00",
    categoryName: "Artists & Musicians",
    categoryDescription: "Person notes for artists, musicians, and creative figures.",
  },
  {
    areaNumber: 74,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "74.00",
    categoryName: "Political Figures",
    categoryDescription: "Person notes for political leaders and public figures.",
  },
  {
    areaNumber: 75,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "75.00",
    categoryName: "Scholars & Academics",
    categoryDescription: "Person notes for scholars, teachers, and academic figures.",
  },
  {
    areaNumber: 76,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "76.00",
    categoryName: "Religious Figures",
    categoryDescription: "Person notes for religious thinkers, teachers, and exemplars.",
  },
  {
    areaNumber: 77,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "77.00",
    categoryName: "Historical Figures",
    categoryDescription: "Person notes for major historical figures outside the other primary lanes.",
  },
  {
    areaNumber: 78,
    areaName: "PEOPLE & BIOGRAPHY",
    areaDescription: "Thinkers, writers, historical actors, and other notable figures tracked as people-centered notes.",
    categoryNumber: "78.00",
    categoryName: "Contemporary Thinkers",
    categoryDescription: "Person notes for living or recent contemporary thinkers.",
  },
  {
    areaNumber: 80,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "80.01",
    categoryName: "Recurring Patterns Across Sources",
    categoryDescription: "Thematic connections that recur across multiple works or domains.",
  },
  {
    areaNumber: 80,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "80.02",
    categoryName: "Unexpected Parallels",
    categoryDescription: "Surprising resonances or parallels between otherwise distant materials.",
  },
  {
    areaNumber: 80,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "80.03",
    categoryName: "Contradictions & Tensions",
    categoryDescription: "Contrasts, frictions, and unresolved tensions between notes or theories.",
  },
  {
    areaNumber: 81,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "81.01",
    categoryName: "Science & Humanities Links",
    categoryDescription: "Connections between scientific and humanistic thought.",
  },
  {
    areaNumber: 81,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "81.02",
    categoryName: "Theory & Practice Links",
    categoryDescription: "Connections between abstract theory and lived or applied practice.",
  },
  {
    areaNumber: 81,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "81.03",
    categoryName: "Ancient & Modern Links",
    categoryDescription: "Connections that bridge historical periods, especially ancient and modern thought.",
  },
  {
    areaNumber: 82,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "82.01",
    categoryName: "Mind Maps of Related Ideas",
    categoryDescription: "Conceptual maps and visual relationship structures.",
  },
  {
    areaNumber: 82,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "82.02",
    categoryName: "Genealogies of Concepts",
    categoryDescription: "Lineages and developmental histories of concepts.",
  },
  {
    areaNumber: 82,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "82.03",
    categoryName: "Networks & Clusters",
    categoryDescription: "Network views and clustered relationships among ideas.",
  },
  {
    areaNumber: 83,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "83.01",
    categoryName: "Notes About Notes",
    categoryDescription: "Meta-notes reflecting on the note collection itself.",
  },
  {
    areaNumber: 83,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "83.02",
    categoryName: "Patterns in Thinking",
    categoryDescription: "Meta-level observations about recurring thought patterns.",
  },
  {
    areaNumber: 83,
    areaName: "CONNECTIONS & SYNTHESIS",
    areaDescription: "The layer where cross-source patterns, conceptual maps, and meta-level synthesis become explicit.",
    categoryNumber: "83.03",
    categoryName: "Evolution of Understanding",
    categoryDescription: "Notes that track how understanding changes over time.",
  },
  {
    areaNumber: 90,
    areaName: "ARCHIVE & COMPLETED",
    areaDescription: "Completed work, retired materials, and long-term archival storage.",
    categoryNumber: "90.00",
    categoryName: "Completed Projects",
    categoryDescription: "Archived records for completed projects and finished initiatives.",
  },
  {
    areaNumber: 91,
    areaName: "ARCHIVE & COMPLETED",
    areaDescription: "Completed work, retired materials, and long-term archival storage.",
    categoryNumber: "91.00",
    categoryName: "Superseded Notes",
    categoryDescription: "Notes intentionally retired or replaced by newer versions.",
  },
  {
    areaNumber: 92,
    areaName: "ARCHIVE & COMPLETED",
    areaDescription: "Completed work, retired materials, and long-term archival storage.",
    categoryNumber: "92.00",
    categoryName: "Historical Archive",
    categoryDescription: "Long-term archival storage for historical materials and completed note sets.",
  },
];

export type JohnnyDecimalAreaSummary = {
  areaNumber: number;
  areaName: string;
  areaDescription: string;
};

export function getJohnnyDecimalAreas(): JohnnyDecimalAreaSummary[] {
  const map = new Map<number, JohnnyDecimalAreaSummary>();

  for (const seed of johnnyDecimalSeeds) {
    if (!map.has(seed.areaNumber)) {
      map.set(seed.areaNumber, {
        areaNumber: seed.areaNumber,
        areaName: seed.areaName,
        areaDescription: seed.areaDescription,
      });
    }
  }

  return Array.from(map.values()).sort((a, b) => a.areaNumber - b.areaNumber);
}

export function getJohnnyDecimalSeedByCategoryNumber(categoryNumber: string) {
  return johnnyDecimalSeeds.find((seed) => seed.categoryNumber === categoryNumber);
}

export const johnnyDecimalModuleDefaults = {
  notebookQuote: "30.09",
  notebookNote: "41.01",
  lexiconGeneral: "10.01",
  lexiconEtymology: "11.01",
  lexiconConcordance: "12.01",
  documentDraft: "45.01",
  goal: "40.01",
  project: "40.01",
  task: "60.03",
  idea: "80.01",
} as const;
